name: GH Actions CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

env:
  CONDA_DEPS: "'MDAnalysis' MDAnalysisTests numpy scipy pytest pytest-xdist pytest-cov codecov"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.11", "3.12", "3.13"]
    env:
      CYTHON_TRACE_NOGIL: 1
      MPLBACKEND: agg
      GH_OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Setup Micromamba"
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          environment-name: mdrg
          create-args: >-
            python=${{ matrix.python-version }}
          init-shell: bash

      - name: install_deps
        run: |
          micromamba install ${{ env.CONDA_DEPS }}

      - name: check_setup
        run: |
          echo ${GH_OS}
          which python
          which conda
          which pip
          micromamba list

      - name: install_mdrg
        run: |
          python -m pip install . --no-deps

      - name: version
        run: |
          python -Ic "import MDRestraintsGenerator; print(MDRestraintsGenerator.__version__)"

      - name: run_tests
        run: |
          pytest -n auto -v --cov=MDRestraintsGenerator --cov-report=xml MDRestraintsGenerator/tests/

      - name: codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: True
          verbose: True
